package com.mlmvpn.scanner.lan

import android.Manifest
import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import android.location.LocationManager
import android.net.wifi.WifiManager
import android.os.Build
import android.provider.Settings
import android.util.Log
import androidx.core.content.ContextCompat

// =================================================================================================
// Getting this phone onto a network the other device can reach.
//
// The obvious answer -- "turn on the hotspot for me" -- is not available to an ordinary app.
// TetheringManager.startTethering() needs TETHER_PRIVILEGED, which is signature|privileged, so the
// only API in reach is WifiManager.startLocalOnlyHotspot(). That deliberately does NOT forward the
// phone's internet to its clients, which reads like a dealbreaker and is not one here: this
// feature never shares internet through the upstream, it shares it through a proxy the client
// dials on the phone's own address. A local-only hotspot gives every client an address on the
// phone's subnet, which is all the proxy needs.
//
// So there are two routes, and the screen offers them in this order:
//
//  1. [start] -- a local-only hotspot, created in-app, SSID and password generated by the system
//     and shown (with a Wi-Fi QR) so the other device can join by camera. No trip to Settings.
//  2. [openSystemTethering] -- the platform's own tethering page, for the devices and Android
//     builds where route 1 is unavailable, and for anyone who would rather share real tethering.
//
// Route 1's costs are real and are stated in the UI rather than discovered: it needs a location
// permission (Android's rule, not ours), it disconnects the phone from any Wi-Fi it had joined,
// several OEMs have removed it, and it stops when the app process does.
// =================================================================================================

object LanHotspot {

    private const val TAG = "LanHotspot"

    /** Held so the hotspot can be stopped again; null when we did not start one. */
    @Volatile
    private var reservation: WifiManager.LocalOnlyHotspotReservation? = null

    /** What a caller needs to fix before [start] can work. */
    enum class Precondition {
        /** Nothing in the way. */
        READY,

        /** The location permission has not been granted yet. */
        NEEDS_PERMISSION,

        /**
         * The permission is granted but location services are switched off device-wide.
         *
         * A separate case because it fails differently and is fixed somewhere else entirely.
         * Android refuses to start a local-only hotspot with location off even for an app that
         * holds the permission, and the callback's failure reason for it is indistinguishable
         * from a generic error -- so it is checked up front instead of guessed at afterwards.
         */
        NEEDS_LOCATION_SERVICE,

        /** This device or Android version cannot do it at all. Use [openSystemTethering]. */
        UNSUPPORTED,
    }

    /** The credentials of a hotspot this app created, for display and for the Wi-Fi QR. */
    data class Credentials(val ssid: String, val password: String) {
        /**
         * The Wi-Fi join string both Android's and iOS's cameras understand.
         *
         * Semicolons and backslashes inside an SSID or password are field separators in this
         * format and have to be escaped, or a password containing one silently joins the wrong
         * network -- or no network, with no error a user could act on.
         */
        val qrPayload: String
            get() = "WIFI:S:${escape(ssid)};T:WPA;P:${escape(password)};;"

        private fun escape(v: String): String =
            v.replace("\\", "\\\\")
                .replace(";", "\\;")
                .replace(",", "\\,")
                .replace(":", "\\:")
                .replace("\"", "\\\"")
    }

    /** True while a hotspot this app started is up. */
    val isOurs: Boolean get() = reservation != null

    /** The permission Android wants for this, which differs by version. */
    fun requiredPermission(): String =
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            Manifest.permission.NEARBY_WIFI_DEVICES
        } else {
            Manifest.permission.ACCESS_FINE_LOCATION
        }

    fun hasPermission(context: Context): Boolean =
        ContextCompat.checkSelfPermission(context, requiredPermission()) ==
            PackageManager.PERMISSION_GRANTED

    /** What stands between the user and a hotspot right now. */
    fun precondition(context: Context): Precondition {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) return Precondition.UNSUPPORTED
        if (context.getSystemService(Context.WIFI_SERVICE) !is WifiManager) {
            return Precondition.UNSUPPORTED
        }
        if (!hasPermission(context)) return Precondition.NEEDS_PERMISSION
        // Only Android 8 to 12 tie this to the location service; from 13 the NEARBY_WIFI_DEVICES
        // permission stands on its own and the toggle is irrelevant.
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU && !locationEnabled(context)) {
            return Precondition.NEEDS_LOCATION_SERVICE
        }
        return Precondition.READY
    }

    private fun locationEnabled(context: Context): Boolean {
        val lm = context.getSystemService(Context.LOCATION_SERVICE) as? LocationManager
            ?: return false
        return runCatching {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
                lm.isLocationEnabled
            } else {
                @Suppress("DEPRECATION")
                lm.isProviderEnabled(LocationManager.NETWORK_PROVIDER) ||
                    lm.isProviderEnabled(LocationManager.GPS_PROVIDER)
            }
        }.getOrDefault(false)
    }

    /**
     * Start a local-only hotspot.
     *
     * [onReady] carries the credentials when they can be read, and null when the hotspot came up
     * but the system would not hand them over -- which happens on a few OEM builds. That is still
     * a success: the client can join from the phone's own Wi-Fi sharing screen, and the proxy will
     * work regardless. Reporting it as a failure would be wrong and would send the user to fix a
     * hotspot that is already running.
     *
     * [onFailed] carries the platform's reason code, or -1 when the call itself threw.
     */
    fun start(
        context: Context,
        onReady: (Credentials?) -> Unit,
        onFailed: (Int) -> Unit,
        onStopped: () -> Unit = {},
    ) {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) {
            onFailed(-1)
            return
        }
        val wifi = context.applicationContext.getSystemService(Context.WIFI_SERVICE) as? WifiManager
        if (wifi == null) {
            onFailed(-1)
            return
        }
        if (reservation != null) {
            onReady(credentialsOf(reservation))
            return
        }
        val callback = object : WifiManager.LocalOnlyHotspotCallback() {
            override fun onStarted(res: WifiManager.LocalOnlyHotspotReservation?) {
                reservation = res
                onReady(credentialsOf(res))
            }

            override fun onStopped() {
                reservation = null
                onStopped()
            }

            override fun onFailed(reason: Int) {
                reservation = null
                Log.w(TAG, "local-only hotspot failed, reason=$reason")
                onFailed(reason)
            }
        }
        try {
            // A null handler puts the callbacks on the main looper, which is where the caller
            // wants them: every one of them updates the screen.
            wifi.startLocalOnlyHotspot(callback, null)
        } catch (e: SecurityException) {
            Log.w(TAG, "no permission for local-only hotspot: ${e.message}")
            onFailed(-1)
        } catch (e: IllegalStateException) {
            // Thrown when tethering is already active, which is not a failure the user needs to
            // do anything about -- they already have the network this was going to create.
            Log.i(TAG, "hotspot already active: ${e.message}")
            onFailed(-1)
        }
    }

    /** Tear down a hotspot this app started. Does nothing to one the user started themselves. */
    fun stop() {
        runCatching { reservation?.close() }
        reservation = null
    }

    private fun credentialsOf(res: WifiManager.LocalOnlyHotspotReservation?): Credentials? {
        if (res == null) return null
        return runCatching {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
                val config = res.softApConfiguration
                val ssid = config.ssid ?: return null
                val pass = config.passphrase ?: return null
                Credentials(ssid, pass)
            } else {
                @Suppress("DEPRECATION")
                val config = res.wifiConfiguration ?: return null
                @Suppress("DEPRECATION")
                Credentials(config.SSID ?: return null, config.preSharedKey ?: return null)
            }
        }.getOrNull()
    }

    // ---------------------------------------------------------------------------------------
    // Route 2: the platform's own screen.
    // ---------------------------------------------------------------------------------------

    /**
     * Open the system's tethering page, falling back through progressively vaguer destinations.
     *
     * The first target is the real tethering screen, which is not part of the public intent
     * surface -- it is a named activity in the Settings app, present on most builds and absent on
     * some. When it is absent the wireless-settings action always exists, and lands the user one
     * level above the switch rather than nowhere at all.
     *
     * @return true when something opened.
     */
    fun openSystemTethering(context: Context): Boolean {
        val targets = listOf(
            Intent().setClassName("com.android.settings", "com.android.settings.TetherSettings"),
            Intent().setClassName(
                "com.android.settings",
                "com.android.settings.Settings\$TetherSettingsActivity",
            ),
            Intent(Settings.ACTION_WIRELESS_SETTINGS),
            Intent(Settings.ACTION_SETTINGS),
        )
        for (intent in targets) {
            intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            if (runCatching { context.startActivity(intent); true }.getOrDefault(false)) return true
        }
        return false
    }

    /** Open the device's location settings, for [Precondition.NEEDS_LOCATION_SERVICE]. */
    fun openLocationSettings(context: Context): Boolean =
        runCatching {
            context.startActivity(
                Intent(Settings.ACTION_LOCATION_SOURCE_SETTINGS)
                    .addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            )
            true
        }.getOrDefault(false)
}
