-- Game Booster crowd service (worker.js). Counters only: no row here describes one person.
CREATE TABLE IF NOT EXISTS agg (
  day INTEGER NOT NULL, asn INTEGER NOT NULL, game TEXT NOT NULL, region TEXT NOT NULL, plan TEXT NOT NULL,
  n INTEGER NOT NULL DEFAULT 0, ok INTEGER NOT NULL DEFAULT 0, bad INTEGER NOT NULL DEFAULT 0,
  wm INTEGER NOT NULL DEFAULT 0, ww INTEGER NOT NULL DEFAULT 0,
  p50s INTEGER NOT NULL DEFAULT 0, p50n INTEGER NOT NULL DEFAULT 0,
  k1 INTEGER NOT NULL DEFAULT 0, k2 INTEGER NOT NULL DEFAULT 0, k3 INTEGER NOT NULL DEFAULT 0,
  k4 INTEGER NOT NULL DEFAULT 0, k5 INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (day, asn, game, region, plan)
) WITHOUT ROWID;
CREATE TABLE IF NOT EXISTS prov (
  day INTEGER NOT NULL, asn INTEGER NOT NULL, game TEXT NOT NULL, prov TEXT NOT NULL,
  ok INTEGER NOT NULL DEFAULT 0, bad INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (day, asn, game, prov)
) WITHOUT ROWID;
CREATE TABLE IF NOT EXISTS lim (k TEXT PRIMARY KEY, day INTEGER NOT NULL, n INTEGER NOT NULL) WITHOUT ROWID;
CREATE TABLE IF NOT EXISTS snap (k TEXT PRIMARY KEY, body TEXT NOT NULL, sig TEXT NOT NULL, at INTEGER NOT NULL) WITHOUT ROWID;
CREATE TABLE IF NOT EXISTS meta (k TEXT PRIMARY KEY, v TEXT) WITHOUT ROWID;
